Repository brave/browser-laptop, pull requests merged in 2018-06, with the labels that each got.

#14266 Adds ballots prepare batching
  package-lock.json
  package.json
Labels: PR/pending-review, feature/rewards

#14311 For Preferences tab, setup events on correct Tab object
  app/browser/tabs.js
Labels: feature/rewards

#14312 Removes fixed input width
  app/renderer/components/preferences/payment/enabledContent.js
Labels: feature/rewards

#14315 Fixes less sort for ledger table
  app/common/state/ledgerState.js
  test/unit/app/common/state/ledgerStateTest.js
Labels: PR/pending-review, feature/rewards

#14314 Clears old entries from the table
  app/browser/api/ledger.js
  app/browser/reducers/ledgerReducer.js
  js/actions/appActions.js
  package-lock.json
  package.json
  test/unit/app/browser/api/ledgerTest.js
  test/unit/app/browser/reducers/ledgerReducerTest.js
Labels: feature/rewards

#14313 Fixing crash when ledger-state.json is missing/corrupted
  app/browser/api/ledger.js
  test/unit/app/browser/api/ledgerTest.js
Labels: PR/pending-review, crash, feature/rewards

#14157 Fixing deletedSites modal not persisting while clearing sites
  app/renderer/components/preferences/payment/deletedSites.js
Labels: feature/rewards

#14324 Adds logic for 90% contribution amount
  app/browser/api/ledger.js
  app/browser/api/ledgerNotifications.js
  app/common/lib/ledgerExportUtil.js
  app/common/lib/ledgerUtil.js
  app/renderer/components/preferences/payment/history.js
  js/about/contributionStatement.js
  test/unit/app/browser/api/ledgerTest.js
  test/unit/app/common/lib/ledgerUtilTest.js
  test/unit/fixtures/exampleLedgerData.js
Labels: feature/rewards

#14328 Release notes for 0.22.x Release 5
  CHANGELOG.md
Labels: QA/no-qa-needed, documentation ✍, release-notes/exclude

#14289 Ensuring http only sites are not added as https in the ledger table
  app/browser/api/ledger.js
  test/unit/app/browser/api/ledgerTest.js
Labels: feature/rewards

#14357 Adds captcha block overlay
  app/browser/api/ledger.js
  app/browser/reducers/ledgerReducer.js
  app/common/constants/promotionStatuses.js
  app/extensions/brave/locales/en-US/preferences.properties
  app/locale.js
  app/renderer/components/preferences/payment/enabledContent.js
  app/sessionStore.js
  js/actions/appActions.js
  test/unit/app/browser/api/ledgerTest.js
  test/unit/app/browser/reducers/ledgerReducerTest.js
Labels: feature/rewards

#14381 Torrent warning tor tabs
  app/browser/webtorrent.js
  app/extensions/brave/locales/en-US/app.properties
  app/filtering.js
  app/locale.js
Labels: feature/tor

#14362 Fixing UGP captcha issues with Windows 10 scaling
  app/renderer/components/preferences/payment/captcha.js
Labels: OS/Windows, PR/pending-review, feature/rewards

#14379 Release notes for 0.22.x C67
  CHANGELOG.md
Labels: QA/no-qa-needed, documentation ✍, release-notes/exclude

#14394 Fixes 0.22.x C67 Release Notes
  CHANGELOG.md
Labels: QA/no-qa-needed, documentation ✍, release-notes/exclude

#14425 Fixing undefined currency value for contribution notification
  app/browser/api/ledgerNotifications.js
Labels: feature/rewards

#14349 Update Linux Mint versions and codenames
  docs/linuxInstall.md
Labels: OS/unix-like/linux, documentation ✍

#14457 Bumping bat-publisher to 2.0.18 (Fixes payments related crash)
  package-lock.json
  package.json
Labels: PR/pending-review, feature/rewards

#14467 add tor menu items, make tor switch per tab
  app/browser/menu.js
  app/browser/reducers/aboutNewTabReducer.js
  app/browser/tabs.js
  app/browser/windows.js
  app/common/commonMenu.js
  app/extensions/brave/locales/en-US/menu.properties
  app/extensions/brave/locales/en-US/newtab.properties
  app/extensions/brave/locales/en-US/preferences.properties
  app/locale.js
  app/renderer/components/main/siteInfo.js
  app/renderer/reducers/contextMenuReducer.js
  app/renderer/reducers/urlBarReducer.js
  app/renderer/rendererShortcutHandler.js
  docs/state.md
  js/about/newprivatetab.js
  js/about/newtab.js
  js/about/preferences.js
  js/constants/appConfig.js
  js/constants/settings.js
  js/contextMenus.js
  js/flash.js
  test/tab-components/torTabTest.js
Labels: PR/needs-QA-attention ☕, feature/tor

#14368 Sites and wallet now cannot be deleted when payment is in progress
  app/extensions/brave/locales/en-US/preferences.properties
  app/locale.js
  app/renderer/components/preferences/payment/advancedSettings.js
  app/renderer/components/preferences/payment/enabledContent.js
  app/renderer/components/preferences/payment/ledgerTable.js
  app/renderer/components/preferences/paymentsTab.js
Labels: PR/pending-review, feature/rewards

#14505 Log will-download event to console
  app/filtering.js
Labels: QA/no-qa-needed

#14507 Adapt package_tor.js to the mingw build of tor.
  package-lock.json
  package.json
  tools/package_tor.js
Labels: feature/tor

#14554 Connect to 127.0.0.1, not localhost, for tor control channel. Tweak error branches for clarity.
  app/tor.js
Labels: feature/tor

#14570 Fixing icon misalignment for ads-trials OSX .dmg
  res/developer/builderConfig.json
Labels: initiative/bat-ads

#14566 Adding install splash screen for developer channel
  res/brave_splash_installing_dev.gif
  tools/buildInstaller.js
Labels: initiative/bat-ads

#14585 Make polling for tor restart work. Call setupTor only once.
  app/filtering.js
  app/tor.js
  test/unit/app/torTest.js
Labels: feature/tor

#14588 Release notes for 0.23.x
  CHANGELOG.md
Labels: QA/no-qa-needed, documentation ✍, release-notes/exclude

#13926 Removing download percentage from downloadItem tooltip
  app/renderer/components/download/downloadItem.js
Labels: bug, feature/download

#14600 Use a different socks port number for channel ''.
  app/channel.js
Labels: feature/tor
