Repository brave/browser-laptop, pull requests merged in 2018-07, with the labels that each got.

#14657 Brave Ads fixes for clear Ads data
  app/browser/api/userModel.js
  app/renderer/components/main/clearBrowsingDataPanel.js
Labels: PR/pending-review

#14621 Moved UGP request delay up to 1 minute.
  app/browser/api/ledger.js
  app/browser/reducers/ledgerReducer.js
  js/actions/appActions.js
  js/constants/appConstants.js
  test/unit/app/browser/api/ledgerTest.js
  test/unit/app/browser/reducers/ledgerReducerTest.js
Labels: PR/pending-review

#14648 Ads Test Fixes (Issue #61/Sections 1 - 3)
  app/browser/api/userModel.js
  app/extensions/brave/locales/en-US/preferences.properties
  app/renderer/about/welcome.js
  app/renderer/components/preferences/ads/disabledContent.js
  res/developer/braveDefaults.nsi
  res/developer/builderConfig.json
  res/developer/linuxPackaging.json
  tools/buildInstaller.js
  tools/buildPackage.js
Labels: PR/pending-review, initiative/bat-ads/ads-test

#14262 Prevents Add Funds overlay from displaying when there is a ledger error
  app/browser/api/ledgerNotifications.js
  app/browser/reducers/ledgerReducer.js
  js/actions/appActions.js
  js/constants/appConstants.js
  test/unit/app/browser/api/ledgerNotificationsTest.js
Labels: feature/rewards

#14668 Start tor lazily, only when a private tab with Tor is created.
  app/filtering.js
Labels: feature/tor

#14599 Take advantage of tor NETWORK_LIVENESS events.
  app/browser/reducers/torReducer.js
  app/filtering.js
  app/renderer/components/main/main.js
  app/renderer/components/main/siteInfo.js
  app/renderer/components/navigation/urlBar.js
  app/tor.js
  docs/state.md
  js/actions/appActions.js
  js/constants/appConstants.js
Labels: feature/tor

#14676 Windows notifications are missing BAT icon when run from full build.
  app/browser/api/userModel.js
  app/extensions/brave/img/BAT_icon.png
Labels: OS/Windows, PR/pending-review, initiative/bat-ads/ads-test

#13187 Refactoring menu
  app/browser/menu.js
  app/browser/reducers/menuReducer.js
  js/stores/appStore.js
  test/unit/app/browser/reducers/menuReducerTest.js
  test/unit/js/stores/appStoreTest.js
Labels: refactoring

#14675 Fix some error branches in tor controller logic.
  app/tor.js
Labels: feature/tor

#14709 Block tab.loadURL in tor tabs until tor is initialized
  app/browser/tabs.js
Labels: feature/tor

#14721 Fix error branches, take 3.
  app/filtering.js
  app/tor.js
  test/integration/app/torTest.js
Labels: feature/tor

#14715 Block loading .onion sites in non-Tor tabs.
  app/extensions/brave/locales/en-US/app.properties
  app/filtering.js
  app/locale.js
Labels: feature/tor

#14614 Increasing coverage - unit tests for dispatchAction + tabs
  test/unit/app/browser/tabsTest.js
  test/unit/app/common/dispatcher/dispatchActionTest.js
Labels: QA/no-qa-needed, automated-tests

#14736 Upgrading bat-client to 3.3.3
  package-lock.json
  package.json
Labels: feature/rewards

#14708 Adding single source support for publisher verification check
  app/browser/api/ledger.js
  app/browser/reducers/ledgerReducer.js
  js/actions/appActions.js
  js/constants/appConstants.js
  test/unit/app/browser/api/ledgerTest.js
Labels: PR/pending-review, feature/rewards, privacy

#14740 Refactors single verified list
  app/browser/api/ledger.js
  app/browser/reducers/ledgerReducer.js
  app/common/state/ledgerState.js
  docs/state.md
  js/actions/appActions.js
  js/constants/appConstants.js
  test/unit/app/browser/api/ledgerTest.js
  test/unit/app/common/state/ledgerStateTest.js
Labels: feature/rewards

#14732 Promotions server should now be polled from payments screen without having payments enabled.
  app/browser/api/ledger.js
  app/browser/reducers/ledgerReducer.js
  js/actions/appActions.js
  js/constants/appConstants.js
  test/unit/app/browser/api/ledgerTest.js
  test/unit/app/browser/reducers/ledgerReducerTest.js
Labels: PR/pending-review, feature/rewards

#14743 Ensuring publishers file is read from as little possible
  app/browser/api/ledger.js
  test/unit/app/browser/api/ledgerTest.js
Labels: feature/rewards

#14761 Release notes for 0.23.x Release 3
  CHANGELOG.md
Labels: QA/no-qa-needed, release-notes/exclude

#14774 Removes PIA
  app/browser/api/ledger.js
  app/extensions/brave/img/private_internet_access.png
  app/extensions/brave/img/private_internet_access_2x.png
  app/extensions/brave/locales/en-US/preferences.properties
  app/renderer/components/preferences/payment/disabledContent.js
  test/unit/app/browser/api/ledgerTest.js
Labels: feature/rewards

#14782 Release notes for 0.23.x Release 3 Updated
  CHANGELOG.md
Labels: QA/no-qa-needed, release-notes/exclude

#14771 Dismissing browser activity notice when browsing time has met/surpassed 30 minutes
  app/browser/api/ledger.js
  app/browser/reducers/ledgerReducer.js
  docs/state.md
  js/actions/appActions.js
  js/constants/appConstants.js
  test/unit/app/browser/api/ledgerTest.js
Labels: PR/pending-review, feature/rewards

#14620 Delaying ref headers fetch until after startup
  app/browser/api/ledger.js
  app/browser/reducers/ledgerReducer.js
  js/actions/appActions.js
  js/constants/appConstants.js
  test/unit/app/browser/api/ledgerTest.js
Labels: feature/rewards

#14751 Using publisher data file for publisher exclusion (removing ruleset code)
  app/browser/api/ledger.js
  package-lock.json
  package.json
  test/taxonomy/exclusionListTest.js
  test/unit/app/browser/api/ledgerTest.js
Labels: feature/rewards

#14888 Release notes for 0.23.x Release 4
  CHANGELOG.md
Labels: QA/no-qa-needed, documentation ✍, release-notes/exclude
