Repository brave/browser-laptop, pull requests merged in 2018-03, with the labels that each got.

#13352 Release notes for 0.21.x
  CHANGELOG.md
Labels: QA/no-qa-needed, release-notes/exclude

#13236 Remove unused deps and update public suffix list
  js/lib/psl.js
  package-lock.json
  package.json
Labels: QA/no-qa-needed

#13265 Prevent borkiness when session-store file is missing perWindowState[].closedFrames
  app/sessionStore.js
  js/stores/appStore.js
  js/stores/windowStore.js
  test/unit/js/stores/appStoreTest.js
  test/unit/js/stores/windowStoreTest.js
Labels: bug

#13291 Ensure a window with no frames is not the last remembered window to restore on next startup
  app/browser/windows.js
  app/cmdLine.js
  app/sessionStoreShutdown.js
  test/unit/app/sessionStoreShutdownTest.js
Labels: OS/Windows, regression

#13279 Fixes backup keys export/import; improves print flow
  app/browser/api/ledger.js
  app/browser/reducers/ledgerReducer.js
  app/browser/tabs.js
  app/extensions/brave/about-printkeys.html
  app/extensions/brave/locales/en-US/app.properties
  app/renderer/about/ledger/printKeys.js
  js/about/entry.js
  js/actions/appActions.js
  js/constants/appConstants.js
  js/constants/messages.js
  js/lib/appUrlUtil.js
Labels: feature/ledger

#13004 Adds required prerequisites needed for building on Solus
  README.md
Labels: OS/unix-like/linux, dev-setup, documentation ✍

#12719 Fix tabs briefly animating too wide after finishing closing some tabs (ver. 2)
  app/renderer/components/tabs/tab.js
Labels: regression, release-notes/exclude

#13328 Fix crash of password reducer
  app/browser/reducers/passwordManagerReducer.js
  test/unit/app/browser/ads/adBlockUtilTest.js
  test/unit/app/browser/reducers/passwordManagerReducerTest.js
  test/unit/app/common/state/bookmarksStateTest.js
  test/unit/app/common/state/ledgerStateTest.js
Labels: priority/P3

#13401 Fix#6470
  less/about/bookmarks.less
Labels: 0.22.x, feature/bookmarks

#13406 Note that Brave can be installed on Debian Stretch
  docs/linuxInstall.md
Labels: documentation ✍

#13411 Fixes location validation
  app/browser/api/ledger.js
Labels: feature/ledger

#13115 Add publishers media info request API
  app/browser/api/ledger.js
  app/extensions.js
  app/extensions/brave/content/scripts/metaScraper.js
  app/extensions/brave/content/scripts/requestHandler.js
  js/lib/request.js
  package-lock.json
  package.json
  test/unit/app/browser/api/ledgerTest.js
  test/unit/app/extensions/brave/content/scripts/requestHandlerTest.js
  tools/test.js
Labels: PR/needs-QA-attention ☕, feature/ledger, priority/P3

#13347 Fixes null error in bat-publisher
  package-lock.json
  package.json
Labels: QA/no-qa-needed, feature/ledger

#12754 Add "forget this domain" feature
  app/browser/reducers/historyReducer.js
  app/extensions/brave/locales/en-US/menu.properties
  app/locale.js
  js/actions/appActions.js
  js/constants/appConstants.js
  js/contextMenus.js
  test/unit/app/browser/reducers/historyReducerTest.js
Labels: feature/context-menu, feature/history

#13326 Improves twitch logging time
  app/browser/api/ledger.js
  app/common/constants/twitchEvents.js
  app/common/lib/ledgerUtil.js
  docs/state.md
  test/unit/app/common/lib/ledgerUtilTest.js
Labels: PR/needs-QA-attention ☕, feature/ledger

#13478 release notes for 0.21.x w/ CR65
  CHANGELOG.md
Labels: QA/no-qa-needed, release-notes/exclude

#12565 Tab style updates x 8
  app/common/state/tabContentState/titleState.js
  app/common/state/tabUIState.js
  app/extensions/brave/img/tabs/close_btn.svg
  app/renderer/components/frame/frame.js
  app/renderer/components/main/main.js
  app/renderer/components/styles/global.js
  app/renderer/components/styles/theme.js
  app/renderer/components/tabs/content/audioTabIcon.js
  app/renderer/components/tabs/content/closeTabIcon.js
  app/renderer/components/tabs/content/favIcon.js
  app/renderer/components/tabs/content/newSessionIcon.js
  app/renderer/components/tabs/content/privateIcon.js
  app/renderer/components/tabs/content/tabIcon.js
  app/renderer/components/tabs/content/tabTitle.js
  app/renderer/components/tabs/pinnedTabs.js
  app/renderer/components/tabs/tab.js
  app/renderer/components/tabs/tabs.js
  app/renderer/components/tabs/tabsToolbar.js
  app/renderer/lib/observerUtil.js
  js/lib/color.js
  js/stores/windowStore.js
  less/window.less
  test/unit/app/common/state/tabContentStateTest/audioStateTest.js
  test/unit/app/common/state/tabContentStateTest/closeStateTest.js
  test/unit/app/common/state/tabUIStateTest.js
  test/unit/app/renderer/components/tabs/content/closeTabIconTest.js
Labels: feature/tab-preview, feature/tabsbar, initiative/ux-harmonization

#13503 Fixes bad state
  app/browser/api/ledger.js
Labels: feature/ledger

#13429 increase version range for pinnedTopSites cleanup
  app/sessionStore.js
Labels: feature/topsites

#13164 Made urlBarIconContainer clickable to display connection info
  app/renderer/components/navigation/urlBar.js
  app/renderer/components/styles/global.js
  less/navigationBar.less
  less/variables.less
Labels: feature/URLbar

#13381 #12770 - Improved styling on promotion component
  app/renderer/components/preferences/payment/enabledContent.js
Labels: feature/ledger

#13525 Fix regression for default favicon color on tab hover
  app/renderer/components/tabs/tab.js
Labels: regression

#13534 release notes for 0.21.24 w/ CR65
  CHANGELOG.md
Labels: QA/no-qa-needed, release-notes/exclude

#13436 Fixes notification shown after toggle
  app/common/state/ledgerState.js
  test/unit/app/common/state/ledgerStateTest.js
Labels: feature/ledger

#13456 Removes redundant code
  app/browser/api/ledger.js
  app/browser/api/ledgerNotifications.js
  test/unit/app/browser/api/ledgerTest.js
Labels: feature/ledger, refactoring

#13445 Adds progress text for a contribution
  app/browser/api/ledger.js
  app/browser/tabs.js
  app/common/state/ledgerState.js
  app/extensions/brave/locales/en-US/preferences.properties
  app/renderer/components/preferences/payment/enabledContent.js
  docs/state.md
  test/unit/app/common/state/ledgerStateTest.js
Labels: feature/ledger

#13556 Adjust some colors to completement new tab / top nav colors
  app/renderer/components/bookmarks/addEditBookmarkHanger.js
  app/renderer/components/common/commonForm.js
  app/renderer/components/common/settings.js
  app/renderer/components/preferences/preferenceNavigation.js
  app/renderer/components/styles/global.js
  app/renderer/components/styles/theme.js
  less/navigationBar.less
  less/variables.less
  less/window.less
Labels: 0.22.x

#13568 Ensure state gets passed into `run` method
  app/browser/api/ledger.js
  test/unit/app/browser/api/ledgerTest.js
Labels: feature/ledger

#13551 Adds broken seed overlay
  app/browser/api/ledger.js
  app/browser/reducers/ledgerReducer.js
  app/browser/tabs.js
  app/common/constants/ledgerStatuses.js
  app/extensions/brave/locales/en-US/preferences.properties
  app/locale.js
  app/renderer/components/preferences/payment/enabledContent.js
  package-lock.json
  package.json
  test/unit/app/browser/api/ledgerTest.js
  test/unit/app/browser/reducers/ledgerReducerTest.js
Labels: feature/ledger

#13576 Fixes recovery dialog
  app/renderer/components/preferences/payment/enabledContent.js
Labels: feature/ledger

#13530 Updates bat libraries
  app/browser/api/ledger.js
  package-lock.json
  package.json
  test/unit/app/browser/api/ledgerTest.js
Labels: feature/ledger

#13519 Add the steps to install Brave on Solus since it got packaged recently
  docs/linuxInstall.md
Labels: OS/unix-like/linux, documentation ✍, installation

#13605 Fixes overlay for corrupted wallet
  app/renderer/components/preferences/payment/enabledContent.js
Labels: feature/ledger

#13607 Fixes recover flow when seed is corrupted
  app/browser/api/ledger.js
  app/common/state/ledgerState.js
  test/unit/app/common/state/ledgerStateTest.js
Labels: feature/ledger

#13211 Make sure we only forget a tab once it is destroyed.
  app/browser/tabs.js
Labels: priority/P4, regression

#13600 Fixes twitch, updated to the new data
  app/browser/api/ledger.js
  app/browser/reducers/ledgerReducer.js
  app/common/constants/twitchEvents.js
  app/common/lib/ledgerUtil.js
  app/filtering.js
  js/actions/appActions.js
  test/unit/app/browser/api/ledgerTest.js
  test/unit/app/common/lib/ledgerUtilTest.js
Labels: feature/ledger

#13621 Adds force load for load url
  app/browser/tabs.js
  app/renderer/components/preferences/payment/enabledContent.js
  js/actions/appActions.js
Labels: feature/ledger

#13437 HSTS Fingerprinting
  app/filtering.js
  app/sessionStore.js
  package-lock.json
  test/unit/app/sessionStoreTest.js
Labels: privacy, security

#13249 Add Other Bookmarks to bookmarks menu.
  app/browser/menu.js
  app/common/lib/menuUtil.js
  app/extensions/brave/locales/en-US/menu.properties
  app/locale.js
  test/unit/app/browser/menuTest.js
Labels: PR/pending-review, feature/bookmarks

#13575 Set correct widevine resource ID
  js/state/contentSettings.js
Labels: security

#13665 Tabs theme color update iteration 3
  app/renderer/components/common/browserButton.js
  app/renderer/components/common/longPressButton.js
  app/renderer/components/tabs/tabs.js
  app/renderer/components/tabs/tabsToolbar.js
  img/toolbar/newtab_btn.svg
  less/button.less
  less/window.less
Labels: design
