Repository brave/browser-laptop, pull requests merged in 2018-02, with the labels that each got.

#13083 Adds promo code to the state
  app/browser/api/ledger.js
  app/browser/reducers/ledgerReducer.js
  app/updater.js
  docs/state.md
  js/actions/appActions.js
  test/unit/app/browser/api/ledgerTest.js
  test/unit/app/browser/reducers/ledgerReducerTest.js
Labels: feature/ledger

#13091 Fix promoCode Regex to include valid suffix
  app/cmdLine.js
  build/pkg-scripts/postinstall
Labels: OS/Windows, OS/macOS

#13103 Fixes disappearing publishers
  app/browser/api/ledger.js
Labels: feature/ledger

#12783 prevent sync modal from forcing focus when switching inputs
  app/renderer/components/preferences/syncTab.js
Labels: feature/sync, initiative/sync

#12726 Adds handler for amounts lower then 0.01 USD
  app/browser/api/ledger.js
  app/common/lib/ledgerUtil.js
  test/unit/app/browser/api/ledgerTest.js
  test/unit/app/common/lib/ledgerUtilTest.js
Labels: feature/ledger

#13111 mac - set file mode and group owner for pkg-installed Brave.app
  build/pkg-scripts/postinstall
Labels: installation

#13107 Fix bookmarking brave default top tile favicon issue.
  app/extensions.js
Labels: feature/bookmarks, misc/favicon

#13073 Fix restart notification bar when changing language setting.
  app/index.js
Labels: PR/pending-review, feature/notificationbar, settings

#13118 New debug menu option - 'Allow Manual Tab Discarding': creates 'Discard' tab context menu command
  app/browser/menu.js
  app/browser/reducers/tabsReducer.js
  app/browser/tabs.js
  js/actions/appActions.js
  js/constants/appConfig.js
  js/constants/appConstants.js
  js/constants/settings.js
  js/contextMenus.js
Labels: feature/tabsbar, perf

#13132 Update pkg-installed app permissions to $USER:admin
  build/pkg-scripts/postinstall
Labels: OS/macOS, installation, release-notes/exclude

#11062 replace momentjs with date-fns
  app/browser/api/ledger.js
  app/browser/bookmarksExporter.js
  app/common/lib/ledgerExportUtil.js
  app/common/lib/ledgerUtil.js
  app/renderer/components/preferences/payment/enabledContent.js
  app/renderer/components/preferences/payment/history.js
  js/about/contributionStatement.js
  package-lock.json
  package.json
  test/about/ledgerPanelAdvancedPanelTest.js
  test/unit/app/common/lib/ledgerExportUtilTest.js
Labels: PR/needs-QA-attention ☕, QA/test-plan-specified, perf, sec-low, security

#13150 Release notes for 0.20.x Hotfix 2
  CHANGELOG.md
Labels: QA/no-qa-needed, release-notes/exclude

#13147 Made urlBarIconContainer clickable to display connection info. Fix #7888
  app/renderer/components/navigation/urlBar.js
  app/renderer/components/styles/global.js
  less/navigationBar.less
  less/variables.less
Labels: PR/pending-review, feature/URLbar

#13078 Adds promo check when opening payments tab
  app/browser/api/ledger.js
Labels: feature/ledger

#13148 perf: log mergeProps 'wasted' time, total time and number of invocations
  app/renderer/components/reduxComponent.js
Labels: initiative/perf, release-notes/exclude

#13055 Fixes stop promotions for notifications
  app/browser/api/ledgerNotifications.js
  test/unit/app/browser/api/ledgerNotificationsTest.js
Labels: feature/ledger

#12438 Create a Buffer Window in order to pre-render and open new windows faster
  app/browser/reducers/windowsReducer.js
  app/browser/windows.js
  app/cmdLine.js
  app/common/lib/browserWindowUtil.js
  app/common/state/pinnedSitesState.js
  app/sessionStore.js
  js/actions/appActions.js
  js/entry.js
  js/state/frameStateUtil.js
  test/unit/app/sessionStoreTest.js
Labels: initiative/perf

#13020 Fixes pinned values when total is not over 100
  app/browser/api/ledger.js
  app/common/state/ledgerState.js
  test/unit/app/browser/api/ledgerTest.js
Labels: feature/ledger

#13161 windows restore in the correct order to ensure correct focused window
  app/browser/windows.js
  app/index.js
  js/entry.js
  js/stores/windowStore.js
  test/unit/lib/fakeWindow.js
Labels: bug, initiative/reduce-bugs, regression

#13182 Adds confirmation dialog upon clicking the trash icon in the ledger table
  app/extensions/brave/locales/en-US/preferences.properties
  app/locale.js
  app/renderer/components/preferences/payment/ledgerTable.js
Labels: feature/ledger

#12767 Fixes publisher exclude after restart
  app/browser/api/ledger.js
Labels: feature/ledger

#13056 Moves Ledger Deleted Sites List to a new dialog
  app/extensions/brave/locales/en-US/preferences.properties
  app/renderer/components/preferences/payment/deletedSites.js
  app/renderer/components/preferences/payment/enabledContent.js
  app/renderer/components/preferences/paymentsTab.js
  app/renderer/components/preferences/shieldsTab.js
  app/renderer/components/preferences/sitePermissionsPage.js
  js/about/preferences.js
Labels: feature/ledger

#13184 Use uintKeySeed for uint conversion
  app/browser/api/ledger.js
Labels: QA/no-qa-needed, feature/ledger, release-notes/exclude

#13153 Improves verified flow
  app/browser/api/ledger.js
  app/browser/reducers/ledgerReducer.js
  app/common/state/ledgerState.js
  js/actions/appActions.js
  js/constants/appConstants.js
  package-lock.json
  package.json
  test/unit/app/browser/api/ledgerTest.js
  test/unit/app/common/state/ledgerStateTest.js
Labels: feature/ledger

#13174 Update OpenSUSE install instructions
  docs/linuxInstall.md
Labels: documentation ✍

#13201 Fixes object scenario for uint
  app/browser/api/ledger.js
  test/unit/app/browser/api/ledgerTest.js
Labels: PR/work-in-progress ⚒, feature/ledger

#13039 Removes transition btc->bat code
  app/browser/api/ledger.js
  app/browser/api/ledgerNotifications.js
  app/browser/reducers/ledgerReducer.js
  app/common/state/migrationState.js
  app/extensions/brave/locales/en-US/app.properties
  app/extensions/brave/locales/en-US/preferences.properties
  app/locale.js
  app/renderer/components/preferences/payment/enabledContent.js
  app/renderer/components/preferences/paymentsTab.js
  app/renderer/components/styles/animations.js
  app/sessionStore.js
  docs/state.md
  js/actions/appActions.js
  js/constants/appConstants.js
  test/unit/app/browser/api/ledgerNotificationsTest.js
  test/unit/app/browser/api/ledgerTest.js
  test/unit/app/browser/reducers/ledgerReducerTest.js
Labels: feature/ledger

#13180 Make error message darker
  less/about/error.less
Labels: 0.23.x, feature/about-pages

#13234 Prevent null key in historySites state
  app/common/lib/historyUtil.js
  app/common/state/historyState.js
  app/renderer/components/frame/frame.js
  test/unit/app/common/lib/historyUtilTest.js
Labels: QA/test-plan-specified, regression

#13244 don't show the welcome tab in the buffer window
  app/browser/reducers/tabsReducer.js
Labels: regression

#13242 When closing last window, make sure buffer window is closed so that app exits
  app/browser/windows.js
Labels: regression

#13205 Fixes long publisher titles breaking the ledger table.
  app/renderer/components/preferences/payment/ledgerTable.js
Labels: feature/ledger

#13269 Fixes torrent merge
  app/filtering.js
Labels: feature/torrent

#13220 Fix urlBar margin gap
  less/navigationBar.less
Labels: 0.21.x, PR/pending-review, feature/URLbar

#13243 Returning to the recovery modal after a wallet recovery failure
  app/renderer/components/preferences/payment/ledgerRecovery.js
  test/about/ledgerPanelAdvancedPanelTest.js
  test/lib/selectors.js
Labels: feature/ledger

#13267 Ensuring that pinned publishers are not unpinned when decimal values are entered for the pin percentage
  app/renderer/components/preferences/payment/pinnedInput.js
Labels: feature/ledger

#13271 Persist pinned tab order when a tab is moved by any means
  app/browser/reducers/pinnedSitesReducer.js
  app/browser/tabs.js
  app/browser/windows.js
  app/common/state/pinnedSitesState.js
  app/renderer/components/tabs/pinnedTabs.js
  app/renderer/components/tabs/tab.js
  js/actions/appActions.js
  js/constants/appConstants.js
  test/lib/brave.js
  test/tab-components/pinnedTabTest.js
  test/unit/app/browser/reducers/pinnedSitesReducerTest.js
Labels: feature/pinned-tabs

#13120 Fix tab auto-discarding ability
  app/browser/activeTabHistory.js
  app/browser/reducers/tabsReducer.js
  app/browser/tabs.js
  app/browser/webContentsCache.js
  app/common/state/tabState.js
  app/renderer/components/frame/frame.js
  js/actions/appActions.js
  js/constants/appConstants.js
  js/stores/windowStore.js
Labels: perf, priority/P1

#13294 Fixes big list overflow
  app/renderer/components/preferences/paymentsTab.js
Labels: feature/ledger

#13292 Fixes low amounts display
  app/common/lib/ledgerUtil.js
  test/unit/app/common/lib/ledgerUtilTest.js
Labels: feature/ledger

#13302 Fix typos in dashboard background image names
  js/data/backgrounds.js
Labels: PR/pending-review, feature/welcome

#13285 Fixes favicons fetch
  app/browser/api/ledger.js
  app/browser/reducers/ledgerReducer.js
  app/common/state/ledgerState.js
  package-lock.json
  package.json
  test/unit/app/browser/api/ledgerTest.js
  test/unit/app/common/state/ledgerStateTest.js
Labels: feature/ledger

#13317 Release notes for 0.20.x Hotfix 3
  CHANGELOG.md
Labels: QA/no-qa-needed, release-notes/exclude

#13321 Fix untranslated recovery code text
  app/extensions/brave/locales/bn-BD/app.properties
  app/extensions/brave/locales/bn-IN/app.properties
  app/extensions/brave/locales/cs/app.properties
  app/extensions/brave/locales/de-DE/app.properties
  app/extensions/brave/locales/en-GB/app.properties
  app/extensions/brave/locales/es/app.properties
  app/extensions/brave/locales/eu/app.properties
  app/extensions/brave/locales/fr-FR/app.properties
  app/extensions/brave/locales/hi-IN/app.properties
  app/extensions/brave/locales/id-ID/app.properties
  app/extensions/brave/locales/it-IT/app.properties
  app/extensions/brave/locales/ja-JP/app.properties
  app/extensions/brave/locales/ko-KR/app.properties
  app/extensions/brave/locales/ms-MY/app.properties
  app/extensions/brave/locales/nl-NL/app.properties
  app/extensions/brave/locales/pl-PL/app.properties
  app/extensions/brave/locales/pt-BR/app.properties
  app/extensions/brave/locales/ru/app.properties
  app/extensions/brave/locales/sl/app.properties
  app/extensions/brave/locales/sv-SE/app.properties
  app/extensions/brave/locales/ta/app.properties
  app/extensions/brave/locales/te/app.properties
  app/extensions/brave/locales/tr-TR/app.properties
  app/extensions/brave/locales/uk/app.properties
  app/extensions/brave/locales/zh-CN/app.properties
Labels: 0.21.x, copy/content/text, feature/ledger

#13324 Fix macOS builds
  tools/buildInstaller.js
  tools/cibuild.py
  tools/upload.py
Labels: Infrastructure, QA/no-qa-needed, release-notes/exclude

#13319 Add Install Error Fix
  docs/linuxInstall.md
Labels: documentation ✍
