Repository brave/browser-laptop, pull requests merged in 2018-04, with the labels that each got.

#13682 Release notes for 0.22.x
  CHANGELOG.md
Labels: QA/no-qa-needed, release-notes/exclude

#13699 Fixes for 0.22.13 release notes
  CHANGELOG.md
Labels: QA/no-qa-needed, release-notes/exclude

#13650 Fixes potential null condition
  app/browser/api/ledger.js
Labels: QA/no-qa-needed, feature/ledger, release-notes/exclude

#13667 Adds promo
  app/browser/api/ledger.js
  app/browser/reducers/ledgerReducer.js
  app/browser/reducers/tabsReducer.js
  app/siteHacks.js
  docs/state.md
  js/actions/appActions.js
  js/constants/appConstants.js
  test/unit/app/browser/api/ledgerTest.js
  test/unit/app/siteHacksTest.js
Labels: feature/ledger

#13756 Adds s-s to the referral code
  app/cmdLine.js
  build/pkg-scripts/postinstall
  build/pkg-scripts/postinstall-test.sh
  test/unit/app/cmdLineTest.js
Labels: feature/ledger

#13784 refactor sync to use brave-crypto
  app/renderer/components/preferences/syncTab.js
  package-lock.json
  package.json
  test/lib/userProfiles.js
Labels: feature/sync, initiative/sync

#13758 Calculate bookmarks bar overflow using css
  app/browser/api/textCalc.js
  app/browser/reducers/bookmarkFoldersReducer.js
  app/browser/reducers/bookmarkToolbarReducer.js
  app/browser/reducers/bookmarksReducer.js
  app/browser/reducers/windowsReducer.js
  app/browser/tabs.js
  app/common/lib/bookmarkToolbarUtil.js
  app/common/lib/bookmarkUtil.js
  app/common/state/bookmarkFoldersState.js
  app/common/state/bookmarkToolbarState.js
  app/common/state/bookmarksState.js
  app/renderer/components/bookmarks/bookmarkToolbarButton.js
  app/renderer/components/bookmarks/bookmarksToolbar.js
  app/renderer/components/styles/global.js
  docs/state.md
  js/actions/appActions.js
  js/constants/appConstants.js
  js/stores/appStore.js
  test/unit/app/browser/reducers/bookmarkFoldersReducerTest.js
  test/unit/app/browser/reducers/bookmarkToolbarReducerTest.js
  test/unit/app/browser/reducers/bookmarksReducerTest.js
  test/unit/app/browser/reducers/windowReducerTest.js
  test/unit/app/common/lib/bookmarkToolbarUtilTest.js
  test/unit/app/common/lib/bookmarkUtilTest.js
  test/unit/app/common/state/bookmarkFoldersStateTest.js
  test/unit/app/common/state/bookmarkToolbarStateTest.js
  test/unit/app/common/state/bookmarksStateTest.js
Labels: bug, refactoring

#13119 add off-by-default application firewall feature
  app/extensions/brave/locales/en-US/preferences.properties
  app/filtering.js
  app/firewall.js
  app/index.js
  js/about/preferences.js
  js/constants/appConfig.js
  js/lib/urlutil.js
  package-lock.json
  package.json
  test/unit/lib/urlutilTest.js
Labels: priority/P2, security

#13385 Reconcile is no longer triggered if there are no publishers in the ledger table.
  app/browser/api/ledger.js
Labels: feature/ledger

#13777 Adds PDF's to the ledger table
  app/browser/api/ledger.js
  js/lib/urlutil.js
  test/unit/app/browser/api/ledgerTest.js
  test/unit/lib/urlutilTest.js
Labels: feature/ledger

#12299 Fixes formatting for YT on shields page
  app/renderer/components/preferences/payment/deletedSites.js
  app/renderer/components/preferences/payment/ledgerTable.js
  app/renderer/components/preferences/paymentsTab.js
  app/sessionStore.js
  docs/state.md
Labels: feature/ledger, feature/shields, priority/P5

#13806 Release notes for 0.22.x Release 2
  CHANGELOG.md
Labels: QA/no-qa-needed, release-notes/exclude

#13809 Release notes for 0.22.x Release 2
  CHANGELOG.md
Labels: QA/no-qa-needed, release-notes/exclude

#13785 Increased a fond size for session tab indicator. Fixes #12349
  app/renderer/components/tabs/content/tabIcon.js
Labels: polish

#13720 Reduces contribution delay time
  app/browser/api/ledger.js
  package-lock.json
  package.json
Labels: QA/no-qa-needed, feature/ledger

#13836 Updated release notes for 0.22.x Release 2
  CHANGELOG.md
Labels: QA/no-qa-needed, release-notes/exclude

#13833 Updates bat-client library
  package-lock.json
  package.json
Labels: feature/ledger

#13834 Fixes twitch event logging
  app/browser/api/ledger.js
  app/common/constants/twitchEvents.js
  app/common/lib/ledgerUtil.js
  test/unit/app/browser/api/ledgerTest.js
  test/unit/app/common/lib/ledgerUtilTest.js
Labels: feature/ledger

#13722 Fixes invalid url error
  js/lib/request.js
Labels: QA/no-qa-needed, feature/ledger

#13743 Removes ledgerPinPercentage setting
  app/browser/api/ledger.js
  app/browser/reducers/ledgerReducer.js
  app/common/state/ledgerState.js
  app/renderer/components/preferences/payment/ledgerTable.js
  app/renderer/components/preferences/payment/pinnedInput.js
  docs/state.md
  js/actions/appActions.js
  js/constants/appConstants.js
  js/state/syncUtil.js
  test/unit/app/browser/api/ledgerTest.js
  test/unit/app/renderer/components/preferences/payments/ledgerTableTest.js
Labels: feature/ledger, refactoring

#13776 Opens add funds overlay when clicking on it in the notification
  app/browser/api/ledgerNotifications.js
Labels: feature/ledger

#13742 Updates recovery dialog text and buttons
  app/extensions/brave/locales/en-US/preferences.properties
  app/renderer/components/preferences/payment/ledgerRecovery.js
  app/renderer/components/preferences/paymentsTab.js
  js/about/preferences.js
Labels: feature/ledger

#13788 Fix automated tests post-0.22.x
  app/cmdLine.js
Labels: QA/no-qa-needed, automated-tests

#13866 Ensure tabs are not created in hidden window and correct window is focused
  app/browser/reducers/tabsReducer.js
  app/browser/reducers/windowsReducer.js
  app/browser/windows.js
  app/cmdLine.js
  app/common/commonMenu.js
  js/actions/appActions.js
  js/constants/appConstants.js
Labels: 0.22.x, regression

#13850 Fixes wallet recovery dialogue re-appearing on relaunch after a successful recovery.
  js/about/preferences.js
Labels: feature/ledger

#13726 Fixes sortTable default sort
  app/renderer/components/common/sortableTable.js
  app/renderer/components/preferences/payment/ledgerTable.js
  package-lock.json
  package.json
Labels: feature/ledger

#13675 Some verified publishers no longer remove green tick at sublevels - Fixes issue #10484
  app/common/state/ledgerState.js
  app/renderer/components/navigation/publisherToggle.js
  package-lock.json
  test/unit/app/common/state/ledgerStateTest.js
Labels: PR/pending-review, feature/ledger

#13744 Fixes width of the balance input
  app/renderer/components/common/textbox.js
  app/renderer/components/preferences/payment/enabledContent.js
Labels: feature/ledger

#13867 Fixes disabled create wallet button
  app/renderer/components/preferences/payment/enabledContent.js
Labels: QA/no-qa-needed, feature/ledger

#13872 Fix URL Normalization code - fixes #13858
  app/common/lib/suggestion.js
  app/extensions/brave/content/scripts/adInsertion.js
  test/unit/app/common/lib/suggestionTest.js
Labels: security

#13877 Bring back ability for menu items to focus or create window without creating a tab
  app/common/commonMenu.js
Labels: 0.22.x, regression

#13914 Fix unittest error on MacOS due to invalid semver
  test/unit/app/sessionStoreTest.js
Labels: QA/no-qa-needed, automated-tests

#13856 Adding context menu item to history and bookmark entries for publisher list inclusion
  app/browser/api/ledger.js
  app/browser/reducers/ledgerReducer.js
  app/common/lib/ledgerUtil.js
  app/extensions/brave/locales/en-US/menu.properties
  app/locale.js
  js/actions/appActions.js
  js/constants/appConstants.js
  js/contextMenus.js
  test/unit/app/browser/api/ledgerTest.js
  test/unit/app/browser/reducers/ledgerReducerTest.js
  test/unit/app/common/lib/ledgerUtilTest.js
Labels: feature/ledger

#13945 release notes for 0.22.x w/ CR66
  CHANGELOG.md
Labels: QA/no-qa-needed, release-notes/exclude

#13504 Implemented notification for user to backup Brave wallet
  app/browser/api/ledger.js
  app/browser/api/ledgerNotifications.js
  app/browser/reducers/ledgerReducer.js
  app/common/lib/ledgerUtil.js
  app/common/state/aboutPreferencesState.js
  app/extensions/brave/locales/en-US/app.properties
  app/locale.js
  app/renderer/components/preferences/payment/ledgerBackup.js
  app/sessionStore.js
  docs/state.md
  js/actions/appActions.js
  js/constants/appConstants.js
  test/unit/app/browser/api/ledgerNotificationsTest.js
  test/unit/app/browser/api/ledgerTest.js
  test/unit/app/browser/reducers/ledgerReducerTest.js
  test/unit/app/common/state/aboutPreferencesStateTest.js
Labels: PR/pending-review, feature/ledger

#13884 Escape key now closes Add Funds dialog
  app/renderer/components/preferences/payment/addFundsDialog/addFundsDialogFooter.js
  app/renderer/components/preferences/payment/advancedSettings.js
  app/renderer/components/preferences/payment/enabledContent.js
  app/renderer/components/preferences/payment/ledgerRecovery.js
  app/renderer/components/preferences/paymentsTab.js
  app/renderer/components/preferences/syncTab.js
  js/about/preferences.js
Labels: PR/pending-review, feature/ledger

#13913 Allowing publisher toggle to include a site outside of the minimum payment requirements
  app/browser/api/ledger.js
  app/browser/reducers/ledgerReducer.js
  app/extensions/brave/locales/en-US/app.properties
  app/renderer/components/navigation/publisherToggle.js
  js/actions/appActions.js
  test/unit/app/browser/reducers/ledgerReducerTest.js
Labels: PR/pending-review, feature/ledger

#13951 Bat-client version bump
  package-lock.json
  package.json
Labels: feature/ledger

#13900 Fixes publisher toggle (heart), button enables after time requirements satisfied.
  app/browser/reducers/ledgerReducer.js
  app/common/lib/ledgerUtil.js
  app/renderer/components/navigation/publisherToggle.js
  js/actions/appActions.js
  js/constants/appConstants.js
  test/unit/app/common/lib/ledgerUtilTest.js
Labels: feature/ledger

#13960 Adding in progress overlay/state for wallet recovery
  app/browser/api/ledger.js
  app/browser/reducers/ledgerReducer.js
  app/common/state/aboutPreferencesState.js
  app/common/state/ledgerState.js
  app/extensions/brave/locales/en-US/preferences.properties
  app/renderer/components/preferences/payment/ledgerRecovery.js
  test/unit/app/browser/api/ledgerTest.js
  test/unit/app/browser/reducers/ledgerReducerTest.js
  test/unit/app/common/state/aboutPreferencesStateTest.js
Labels: PR/pending-review, feature/ledger, initiative/bat-payments
