Repository brave/browser-laptop, pull requests merged in 2018-05, with the labels that each got.

#13848 Cleanup of the eopkg commands on Solus for more simplicity
  README.md
Labels: OS/unix-like/linux, dev-setup, documentation ✍

#13973 Adds server problem overlay
  app/browser/api/ledger.js
  app/browser/reducers/ledgerReducer.js
  app/common/constants/ledgerStatuses.js
  app/extensions/brave/locales/en-US/preferences.properties
  app/locale.js
  app/renderer/components/preferences/payment/enabledContent.js
  js/actions/appActions.js
  js/constants/appConstants.js
  test/unit/app/browser/api/ledgerTest.js
Labels: feature/ledger

#13514 Fix typo
  app/extensions/brave/locales/en-US/preferences.properties
Labels: copy/content/text, documentation ✍

#13717 add WordCountTextArea component for ledger and sync
  app/extensions/brave/locales/en-US/preferences.properties
  app/extensions/brave/locales/en-US/styles.properties
  app/renderer/components/common/clipboardButton.js
  app/renderer/components/common/textbox.js
  js/about/styles.js
Labels: feature/ledger, feature/sync

#13933 Ensuring File > Share context menu items are disabled when no windows are open
  app/browser/menu.js
  app/browser/share.js
  app/common/commonMenu.js
  app/common/lib/menuUtil.js
  test/unit/app/common/lib/menuUtilTest.js
Labels: feature/context-menu, refactoring

#14002 Fixes broken seed overlay trigger
  app/browser/api/ledger.js
  test/unit/app/browser/api/ledgerTest.js
Labels: PR/pending-review, feature/ledger

#13774 Fix URL bar
  less/navigationBar.less
Labels: polish

#14022 Fixes contribution process
  app/browser/api/ledger.js
  app/common/lib/ledgerUtil.js
  app/renderer/components/preferences/payment/enabledContent.js
  app/renderer/components/preferences/paymentsTab.js
  test/unit/app/browser/api/ledgerTest.js
Labels: feature/ledger

#14027 Add support for deploying to Ubuntu 18 LTS compatible repositories
  tools/upload_to_aptly
Labels: OS/unix-like/linux

#14028 Implemented fix to show publisher toggle for PDFs
  app/common/lib/publisherUtil.js
  app/renderer/components/navigation/publisherToggle.js
Labels: PR/pending-review, feature/ledger

#14017 Fixing recovery progress indicator showing before a recovery file has been loaded.
  app/browser/api/ledger.js
  app/browser/reducers/ledgerReducer.js
  app/common/state/aboutPreferencesState.js
  test/unit/app/browser/api/ledgerTest.js
  test/unit/app/browser/reducers/ledgerReducerTest.js
  test/unit/app/common/state/aboutPreferencesStateTest.js
Labels: feature/ledger

#14010 Adding re-inclusion for deleted publishers via context menu.
  app/browser/api/ledger.js
  app/common/lib/ledgerUtil.js
  test/unit/app/browser/api/ledgerTest.js
  test/unit/app/common/lib/ledgerUtilTest.js
Labels: PR/pending-review, feature/ledger

#14034 Added test for shouldShowPublisherButton for PR #14028
  test/unit/app/common/lib/publisherUtilTest.js
Labels: QA/no-qa-needed, release-notes/exclude

#13563 Add feature window.prompt
  app/browser/tabMessageBox.js
  app/extensions/brave/locales/en-US/menu.properties
  app/locale.js
  app/renderer/components/common/messageBox.js
  app/renderer/components/common/textbox.js
  test/unit/app/browser/tabMessageBoxTest.js
  test/unit/app/renderer/components/common/messageBoxTest.js
Labels: PR/pending-review

#14006 Notify users when contribution date is pushed back
  app/browser/api/ledger.js
  app/browser/reducers/ledgerReducer.js
  app/common/constants/ledgerStatuses.js
  app/common/lib/ledgerUtil.js
  app/extensions/brave/locales/en-US/preferences.properties
  js/actions/appActions.js
  js/constants/appConstants.js
  package-lock.json
  package.json
  test/unit/app/browser/reducers/ledgerReducerTest.js
  test/unit/app/common/lib/ledgerUtilTest.js
Labels: feature/ledger

#14048 Hide bookmark bar when removing last item
  app/browser/reducers/bookmarkFoldersReducer.js
  app/browser/reducers/bookmarksReducer.js
  app/common/lib/bookmarkUtil.js
  js/settings.js
  test/unit/app/browser/reducers/bookmarkFoldersReducerTest.js
  test/unit/app/browser/reducers/bookmarksReducerTest.js
  test/unit/app/common/lib/bookmarkUtilTest.js
Labels: feature/bookmarks

#14056 Updated recoveryOverlay style to remove focus outline.
  app/renderer/components/preferences/payment/ledgerRecovery.js
Labels: PR/pending-review, feature/ledger

#14057 Fixes fuzzing push back
  package-lock.json
  package.json
Labels: feature/ledger

#14061 Ensure type-safety with tab audio muting
  app/browser/tabs.js
  app/renderer/reducers/contextMenuReducer.js
  js/contextMenus.js
Labels: bug, crash

#14068 Update BAT-client to 2.3.1
  package-lock.json
  package.json
Labels: feature/ledger, security

#13592 Finished Aphrodite restyle of safebrowsing.js. Fixes issue #9025
  app/renderer/components/styles/globalSelectors.js
  js/about/safebrowsing.js
Labels: refactoring/aphrodite

#13783 Do not create a new <webview> element or <Frame /> component for each Tab (single-webview)
  .npmrc
  app/browser/menu.js
  app/browser/reducers/tabsReducer.js
  app/browser/tabs.js
  app/browser/windows.js
  app/cmdLine.js
  app/common/actions/tabActions.js
  app/common/constants/tabAction.js
  app/common/state/frameState.js
  app/common/state/tabState.js
  app/common/state/urlBarState.js
  app/extensions/brave/content/scripts/themeColor.js
  app/index.js
  app/renderer/components/common/contextMenu/contextMenu.js
  app/renderer/components/common/contextMenu/contextMenuItem.js
  app/renderer/components/frame/frame.js
  app/renderer/components/frame/fullScreenWarning.js
  app/renderer/components/frame/guestInstanceRenderer.js
  app/renderer/components/main/findbar.js
  app/renderer/components/main/main.js
  app/renderer/components/tabs/pinnedTabs.js
  app/renderer/components/tabs/tab.js
  app/renderer/components/tabs/tabs.js
  app/renderer/pooledWebviewDisplay.js
  app/renderer/reducers/frameReducer.js
  app/renderer/rendererFrameTracker.js
  app/renderer/rendererShortcutHandler.js
  app/renderer/rendererTabEvents.js
  app/renderer/webviewDisplay.js
  app/sessionStore.js
  docs/state.md
  js/actions/appActions.js
  js/actions/webviewActions.js
  js/actions/windowActions.js
  js/constants/appConfig.js
  js/constants/appConstants.js
  js/constants/settings.js
  js/constants/windowConstants.js
  js/entry.js
  js/state/frameStateUtil.js
  js/stores/appStore.js
  js/stores/windowStore.js
  less/window.less
  test/unit/app/browser/reducers/tabsReducerTest.js
  test/unit/app/browser/tabsTest.js
  test/unit/app/common/lib/historyUtilTest.js
  test/unit/app/common/state/tabStateTest.js
  test/unit/app/renderer/components/frame/frameTest.js
  test/unit/lib/fakeTab.js
  tools/cibuild.py
  webpack.config.js
Labels: initiative/perf

#14106 Revert "Merge pull request #13726 from NejcZdovc/fix/#13721-sort"
  app/renderer/components/common/sortableTable.js
  app/renderer/components/preferences/payment/ledgerTable.js
  package-lock.json
  package.json
Labels: QA/no-qa-needed, release-notes/exclude

#14114 Update documentation for `Running Brave`
  README.md
Labels: QA/no-qa-needed, documentation ✍, release-notes/exclude

#14115 Add support for Debian Buster
  tools/upload_to_aptly
Labels: OS/unix-like/linux, QA/no-qa-needed, release-notes/exclude

#14094 Fixed recovery overlay showing invalid amount before completion
  app/browser/api/ledger.js
  app/common/state/aboutPreferencesState.js
  app/extensions/brave/locales/en-US/preferences.properties
  app/renderer/components/preferences/payment/ledgerRecovery.js
  docs/state.md
  test/unit/app/browser/api/ledgerTest.js
  test/unit/app/common/state/aboutPreferencesStateTest.js
Labels: feature/ledger

#14073 Change facebook top tile to github and improve styling of top tiles icons
  app/extensions.js
  app/extensions/brave/img/newtab/defaultTopSitesIcon/facebook.png
  app/extensions/brave/img/newtab/defaultTopSitesIcon/github.png
  app/extensions/brave/img/newtab/defaultTopSitesIcon/playstore.png
  js/data/newTabData.js
Labels: feature/newtab

#14132 autoplay notification should follow spec
  app/browser/reducers/autoplayReducer.js
Labels: feature/autoplay, feature/notificationbar

#14050 Travis job optimisations
  .travis.yml
  package.json
Labels: QA/no-qa-needed, release-notes/exclude

#14142 Fix unit tests master
  test/unit/app/browser/api/topSitesTest.js
  test/unit/app/browser/reducers/autoplayReducerTest.js
  test/unit/app/common/lib/bookmarkUtilTest.js
Labels: automated-tests

#14153 Release notes for 0.22.x Release 3
  CHANGELOG.md
Labels: QA/no-qa-needed, release-notes/exclude

#14183 Fix typos in docs/style.md
  docs/style.md
Labels: QA/no-qa-needed, documentation ✍, polish, release-notes/exclude

#14134 Fixes disabled torrent viewer torrent download
  app/common/state/extensionState.js
  app/filtering.js
  js/stores/appStore.js
  test/unit/app/common/state/extensionStateTest.js
Labels: feature/torrent

#14193 Adds nsp to travis checks
  .travis.yml
  package-lock.json
  tools/test.js
Labels: QA/no-qa-needed, dev-setup, release-notes/exclude, security

#14146 Talk to the control socket using my old draft tor daemon manager.
  app/filtering.js
  app/tor.js
  test/unit/app/torTest.js
Labels: feature/tor

#14218 Fixes WebTorrent not being enabled
  app/common/state/extensionState.js
  test/unit/app/common/state/extensionStateTest.js
Labels: feature/torrent

#14191 Adds batch voting
  package-lock.json
  package.json
Labels: feature/rewards

#14246 Release notes for 0.22.x Release 4
  CHANGELOG.md
Labels: QA/no-qa-needed, documentation ✍, release-notes/exclude

#14248 Fixed a mistake in the 0.22.x Release 4 notes
  CHANGELOG.md
Labels: QA/no-qa-needed, documentation ✍, release-notes/exclude

#14189 Adds captcha to UGP flow
  app/browser/api/ledger.js
  app/browser/reducers/ledgerReducer.js
  app/common/constants/promotionStatuses.js
  app/common/state/ledgerState.js
  app/extensions/brave/img/ledger/BAT_captcha_BG_arrow.png
  app/extensions/brave/img/ledger/BAT_captcha_dragicon.png
  app/extensions/brave/locales/en-US/preferences.properties
  app/renderer/components/preferences/payment/captcha.js
  app/renderer/components/preferences/payment/enabledContent.js
  js/actions/appActions.js
  js/constants/appConstants.js
  package-lock.json
  package.json
  test/unit/about/preferencesTest.js
  test/unit/app/browser/api/ledgerTest.js
  test/unit/app/browser/reducers/ledgerReducerTest.js
  test/unit/app/common/state/ledgerStateTest.js
  test/unit/app/renderer/components/preferences/paymentsTabTest.js
Labels: PR/pending-review, feature/rewards

#14251 Adds balance breakdown
  app/browser/api/ledger.js
  app/common/lib/ledgerUtil.js
  app/extensions/brave/locales/en-US/preferences.properties
  app/renderer/components/preferences/payment/enabledContent.js
  app/renderer/components/preferences/paymentsTab.js
  docs/state.md
  test/unit/app/browser/api/ledgerTest.js
  test/unit/app/common/lib/ledgerUtilTest.js
  test/unit/app/renderer/components/preferences/paymentsTabTest.js
Labels: PR/pending-review, feature/rewards

#14260 Removes site settings for delete sites
  app/browser/reducers/siteSettingsReducer.js
  app/renderer/components/preferences/payment/deletedSites.js
  test/unit/app/browser/reducers/siteSettingsReducerTest.js
Labels: PR/pending-review, feature/rewards

#14234 Improves prooofing time when doing contribution
  app/browser/api/ledger.js
  package-lock.json
  package.json
  test/unit/app/browser/api/ledgerTest.js
Labels: PR/pending-review, feature/rewards

#14264 Removes ballots delays
  package-lock.json
  package.json
Labels: PR/pending-review, feature/rewards

#14277 Removes drag from arrow
  app/renderer/components/preferences/payment/captcha.js
Labels: PR/pending-review, feature/rewards

#14293 Save empty grants as well
  app/browser/api/ledger.js
  test/unit/app/browser/api/ledgerTest.js
Labels: feature/rewards

#14294 Fixes captcha clear on tab close/restart
  app/browser/api/ledger.js
  app/sessionStore.js
  test/unit/app/browser/api/ledgerTest.js
Labels: PR/pending-review, feature/rewards

#14296 Fixes display name for contributions
  app/browser/api/ledger.js
  app/browser/api/ledgerNotifications.js
  app/locale.js
  js/about/contributionStatement.js
  test/unit/app/browser/api/ledgerTest.js
Labels: PR/pending-review, feature/rewards
