Repository brave/browser-laptop, pull requests merged in 2018-08, with the labels that each got.

#14950 Release notes for 0.23.x Hotfix
  CHANGELOG.md
Labels: QA/no-qa-needed, release-notes/exclude

#14970 Add content setting for media device access
  app/extensions/brave/content/scripts/navigator.js
  js/state/contentSettings.js
Labels: security

#14987 Release notes for 0.23.x Hotfix 2
  CHANGELOG.md
Labels: QA/no-qa-needed, release-notes/exclude

#15000 Adds debug for ledger roundtrip calls
  app/browser/api/ledger.js
Labels: feature/rewards

#13389 About brave clipboard copy now starts at top line - fixes issue #13355
  js/about/brave.js
Labels: misc/clipboard

#15029 Harden use of geth
  app/ethWallet-geth.js
Labels: feature/ETH-Wallet

#15027 eth-wallet: password flow based on the hash stored on the fs
  app/ethWallet-geth.js
  package-lock.json
  package.json
Labels: feature/ETH-Wallet

#15022 delete did-detach block accidentally brought back in #14734
  app/browser/tabs.js
Labels: feature/ETH-Wallet

#15032 Removing --cache.database arg
  app/ethWallet-geth.js
Labels: feature/ETH-Wallet

#15033 Fixes ENOENT issues on Windows
  app/ethWallet-geth.js
Labels: OS/Windows, feature/ETH-Wallet

#15068 Removes delay for referral
  app/browser/api/ledger.js
  test/unit/app/browser/api/ledgerTest.js
Labels: feature/rewards

#15076 block chrome://brave URL loads
  app/browser/tabs.js
Labels: security

#15077 Removes shadow
  app/extensions/brave/img/ledger/BAT_captcha_dragicon.png
  app/renderer/components/preferences/payment/captcha.js
Labels: feature/rewards

#15105 Release notes for 0.23.x Release 5
  CHANGELOG.md
Labels: QA/no-qa-needed, release-notes/exclude

#15131 Release notes for 0.23.x Hotfix 3
  CHANGELOG.md
Labels: QA/no-qa-needed, release-notes/exclude
